### ISSUE TITLE
Exe does not start after setup

### ISSUE THREAD

**Issue by JbmmMx** [ChrisdeG/MendixBackupRestore#1]
Version 3.2.3
After filling in partial settings (API key was succesfull),  I entered the PostgreS path and then it crashed (silent)
Since then starting the exe does not respond anymore (rebooted). 
Settings incorrect? Where can I reset this.

**Comment by ChrisdeG** [comment]
Hi Jeroen,

Use regedit to delete or rename this key from the registry 

Computer\HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\main\java\com\ccdg

And restart the program. I am curious what values you filled in.

Regards,
Chris

**Comment by JbmmMx** [comment]
Hi Chris,

Clearing the variable
pgdir = "/C:///Program /Files//pg/Admin 4//v4//runtime"
did the trick.

Now the Tool setting displays C:\Program Files/PostgreSQL/9.6
In RegEdit pgdir=/C:///Program /Files\/Postgre/S/Q/L\9.6

So:

  1.  I think the quotes are the problem, I assume a wrong path just results in the Tool not finding postgres.
  2.  Postgres <> Pgadmin
  3.  I can still break all software 😊


Met vriendelijke groet / Kind regards,

Jeroen van Bemmelen
Sr. Software Engineer

Tel: +31 88 988 90 00 - Mobiel: +31 6 29479439 - ***@***.******@***.***>

**Comment by ChrisdeG** [comment]
Issues was solved long time ago
