### ISSUE TITLE
No file to download. Server replied HTTP code: 500

### ISSUE THREAD

**Issue by brankosandifort** [ChrisdeG/MendixBackupRestore#2]
Hi Chris,

We have a problem with downloading a back-up file with the restore tool. We receiving a 500 error code. Is there an update with de Mendix interface and is the restore tool not up to date or is there a problem at Mendix?

![image](https://user-images.githubusercontent.com/76212873/178248833-52e159a7-3c4d-4dbd-8c8f-f218f7353d71.png)

**Comment by ChrisdeG** [comment]
Hi Branko, I have seen this error. It has something to with a Sandbox project in the list. Next week I will provide a fix for this.

**Comment by brankosandifort** [comment]
Hi Chris, do you have an update about the problem?

**Comment by ChrisdeG** [comment]
Is fixed in 3.5.0. upgrade to Api V2
